name: QuickVoid
version: 1.0.0
main: com.github.aitooor.quickvoid.QuickVoidPlugin
description: A plugin that allows admins to create void worlds without using a plugin implemented chunks generator.
authors:
  - inc0g-repoz
  - Aitooor
depend:
  - Multiverse-Core

commands:
  quickvoid:
    aliases: [qv]
    descriptions: Reveals plugin functionality
    permission: quickvoid.admin
    usage: "Usage: /<command> <create> <world_name>"

permissions:
  quickvoid.admin:
    description: Allows you to use /quickvoid command